version: "3.2"

services:
  housing-finance-interim-api:
    image: housing-finance-interim-api
    build:
      context: HousingFinanceInterimApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Server=dev-database;Database=testdb;User Id=myuser;Password=mypassword
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: microsoft/mssql-server-windows-express
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  housing-finance-interim-api-test:
    image: housing-finance-interim-api-test
    build:
      context: .
      dockerfile: HousingFinanceInterimApi.Tests/Dockerfile
    environment:
      - DB_SERVER=test-database
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 1433:1433
    env_file:
      - database.env
